Update cache/restore/action.yaml

diff --git a/cache/restore/action.yaml b/cache/restore/action.yaml
--- a/cache/restore/action.yaml
+++ b/cache/restore/action.yaml
@@ -14,6 +14,5 @@ runs:
     - name: Create cache
       run: |
         [ ! -f "/cache/$GITHUB_REPOSITORY/${{ inputs.key }}/archive.tar.gz" ] && echo "Cache not found" && exit
-        tar --overwrite -xzf "/cache/$GITHUB_REPOSITORY/${{ inputs.key }}/archive.tar.gz"
-        echo "Cache restored: /cache/$GITHUB_REPOSITORY/${{ inputs.key }}/archive.tar.gz"  
+        tar --overwrite -xzf "/cache/$GITHUB_REPOSITORY/${{ inputs.key }}/archive.tar.gz" && echo "Cache restored: /cache/$GITHUB_REPOSITORY/${{ inputs.key }}/archive.tar.gz" || echo "Failed..."
       shell: sh  
